name: Test localgovdrupal drupal-module

on:
  workflow_call:
    inputs:
      project:
        description: 'LocalGov Drupal module name'
        required: true
        type: string
      project_path:
        description: 'LocalGov Drupal module path'
        required: true
        type: string

jobs:
  build:
    name: Install LocalGov Drupal
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        localgov-version:
          - '3.x'
        drupal-version:
          - '~10.0'
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'

    steps:
      - name: Running
        run: |
          echo ${{inputs.project}}
          echo ${[inputs.project-path}}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Clone drupal_container
        uses: actions/checkout@v4
        with:
          repository: localgovdrupal/drupal-container
          ref: php${{ matrix.php-version }}

      - name: Create LocalGov Drupal project
        run: |
          composer create-project --stability dev --no-install localgovdrupal/localgov-project ./html "${{ matrix.localgov-version }}"
          composer --working-dir=./html require --no-install localgovdrupal/localgov:${{ matrix.localgov-version }}-dev
          composer --working-dir=./html require --no-install drupal/core-recommended:${{ matrix.drupal-version }} drupal/core-composer-scaffold:${{ matrix.drupal-version }} drupal/core-project-message:${{ matrix.drupal-version }} drupal/core-dev:${{ matrix.drupal-version }}
          composer --working-dir=./html install